#!/bin/bash
#SBATCH --job-name=heat_poly         # Job name
#SBATCH --mail-type=END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=weugene@mail.ru  # Where to send mail.  Set this to your email address
#SBATCH --cpus-per-task=1            # Number of cores per MPI task 
#SBATCH --nodes=1                    # Maximum number of nodes to be allocated
#SBATCH --ntasks-per-node=35         # Maximum number of tasks on each node
#SBATCH --mem-per-cpu=10gb           # Memory (i.e. RAM) per processor
#SBATCH --time=1-00:00:00            # Wall time limit (days-hrs:min:sec)
#SBATCH --output=mpi_test_%j.log     # Path to the standard output and error files relative to the working directory
#SBATCH -p htc
echo $BASILISK

echo "Date              = $(date)"
echo "Hostname          = $(hostname -s)"
echo "Working Directory = $(pwd)"
echo ""
echo "Number of Nodes Allocated      = $SLURM_JOB_NUM_NODES"
echo "Number of Tasks Allocated      = $SLURM_NTASKS"
echo "Number of Cores/Task Allocated = $SLURM_CPUS_PER_TASK"

module load intel/2020

cd $HOME/basilisk/work/Heat_transfer_Polymerization/big_cold_small_bubble/
#qcc -DDUMP=1 -Wall -O2 -events -g -lm poly_heat.c
CC99='mpicc -std=c99' qcc -DDUMP=1 -Wall -O2 -events -lm -D_MPI=1  poly_heat.c
Tcyl=280
maxlevel=10
iter_fp=2
ratio_Rbmin=0.166666
ratio_Rbmax=0.75
ratio_dist_x=2
ratio_dist_y=2
Nb=10
Ncx=5
Ncy=7
mpirun ./a.out $Tcyl $maxlevel $iter_fp $ratio_Rbmin $ratio_Rbmax $ratio_dist_x $ratio_dist_y $Nb $Ncx $Ncy 
